services:
  backend:
    build:
      context: ./MyBackendApp
    container_name: my-backend-app
    ports:
      - "5218:5218"
    networks:
      - app-network

  frontend:
    build:
      context: ./MyFrontendApp
    container_name: my-frontend-app
    ports:
      - "3000:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
